import javax.swing.*;
class Scratch {
    public static void main(String[] args) {
        String[] a = new String[9];
        Scratch sc = new Scratch();
        a[0] = "the goat(){";
        a[1] = "the goat(){}";
        a[2] = "the goat";
        a[3] = "the goat(){;";
        a[4] = "the goat(){";
        a[5] = "the goat";
        a[6] = "the goat";
        a[7] = "the goat()";
        a[8] = "the goat(";

        for(int i = 0; i < a.length; i++) {
            sc.endStatement(a[i]);
        }
    }
    // this function takes in a string and checks the last character of the string to see if statements and methods are
    // properly closed
    int endStatement(String theStr){
        char last = theStr.charAt(theStr.length() - 1);
        // if statement that determines if statement has ended properly
        if(last == ';' || last == '{' || last == '(' || last == ')' || last =='}' ){
            return 1;
        }else {
            JOptionPane optionPane = new JOptionPane("The test program cannot be generated by the Demo function." +
                    " User is missing an end statement.",
                    JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog("Failure");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
            return 0;
        }
    }
}
