/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg360_1;

import java.io.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Abdul
 */
public class Main {

    /**
     * @param args the command line arguments
     */
    ArrayList<String> lexemes = new ArrayList<String>();
    ArrayList<String> tokens = new ArrayList<String>();

    public static void main(String[] args) {
        // TODO code application logic here
        Main r = new Main();

        try {

            File file = new File("360_txt.txt");
            Scanner sc = new Scanner(file);

            String datatype;
            while (sc.hasNext()) {
                datatype = sc.nextLine();
                String[] u = datatype.split(" ");

                //System.out.print(datatype);

                if (!datatype.isEmpty()) {
                    r.endStatement(datatype);
                }
                for (int i = 0; i < u.length; i++) {
                    r.isDataType(u[i]);
                    //System.out.println(u[i]);
                }

                System.out.println();
            }

        } catch (Exception e) {
            System.out.println("error error error");
        }

    }

    public void isDataType(String x) {
        int n = 0;

        if (x.contains(
                "double")) {
            lexemes.add("double");
            System.out.print("<ident> ");
            n++;
        }

        if (x.contains(
                "int")) {
            lexemes.add("int");
            System.out.print("<ident> ");
            n++;
        }

        if (x.contains(
                "char")) {
            lexemes.add("char");
            System.out.print("<ident> ");
            n++;
        }

        if (x.contains(
                "string")) {
            lexemes.add("String");
            System.out.print("<ident> ");
            n++;
        }

        if (x.contains(
                "float")) {
            lexemes.add("float");
            System.out.print("<ident> ");
            n++;
        }

        if (x.contains(
                "long")) {
            lexemes.add("long");
            System.out.print("<ident> ");
            n++;
        }

        if (n > 1) {
            JOptionPane.showMessageDialog(null, "will not run 001");
        } else{
        System.out.print(x);
        }

        // return n;
    }

    // this function takes in a string and checks the last character of the string to see if statements and methods are
    // properly closed
    void endStatement(String theStr) {
        char last = theStr.charAt(theStr.length() - 1);

        // if statement that determines if statement has ended properly
         if(last == ';' || last == '{' || last == '(' || last == ')' || last =='}' ){
            //System.out.println("   YES ");
        } else {
            //JOptionPane.showMessageDialog(null, "The test program cannot be generated by the Demo function.  User is missing an end statement.");
            System.out.println("   NO ");
        }
    }

}
